name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    if: ${{ hashFiles('tests/e2e/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            tests/e2e/pnpm-lock.yaml

      - name: Install deps
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile || true; fi
          if [ -f tests/e2e/pnpm-lock.yaml ]; then pnpm -C tests/e2e install --frozen-lockfile; fi

      - name: Install Playwright (browsers + deps)
        run: pnpm -C tests/e2e exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm -C tests/e2e test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/playwright-report
          if-no-files-found: ignore
