name: E2E (Playwright)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (workspace)
        run: pnpm install

      - name: Build web (prod)
        run: pnpm -C apps/web build

      - name: Install Playwright browsers
        run: pnpm -C tests/e2e exec playwright install --with-deps

      - name: Start API (background)
        run: pnpm -C apps/api dev & echo $! > api.pid

      - name: Wait for API
        run: npx --yes wait-on http://localhost:3000/healthz

      - name: Run Playwright (preview mode)
        run: pnpm -C tests/e2e test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/playwright-report

      - name: Stop API
        if: always()
        run: kill $(cat api.pid) || true

